version: '3'
services:
  analyser:
    build:
      dockerfile: ./docker/analyser.dockerfile
      context: .
    image: mtrentz/analyser
    container_name: analyser
    volumes:
      - ./imgs:/app/imgs
      - ./files:/app/files
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - imgur_net
    ports:
      - "8005:8005"

  downloader:
    build:
      dockerfile: ./docker/downloader.dockerfile
      context: .
    image: mtrentz/downloader
    container_name: downloader
    volumes:
      - ./imgs:/app/imgs
      - ./files:/app/files
    ports:
      - "8006:8006"
    networks:
      - imgur_net
    depends_on: 
      - "analyser"

networks:
  imgur_net:
    driver: bridge